packages:
  - "!**/test/**"
  - "docs"
  - "app"

catalog:
  "@arethetypeswrong/cli": ^0.18.2
  "@next/third-parties": ^14.2.33
  "@types/node": ^24.10.0
  "@vercel/speed-insights": ^1.0.10
  "@vitest/ui": ^4.0.8
  autoprefixer: ^10.4.16
  clsx: ^2.1.1
  eslint: ^9.39.1
  jsdom: ^27.1.0
  next: ^14.2.33
  nextra: ^2.13.4
  nextra-theme-docs: ^2.13.4
  postcss: ^8.4.32
  react: ^18.3.1
  react-dom: ^18.3.1
  standard-changelog: ^7.0.1
  tailwindcss: ^3.4.3
  tsup: ^8.5.0
  typescript: ^5.9.3
  vite-tsconfig-paths: ^5.1.4
  vitest: ^4.0.8
